//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;

    public partial class PersonModel
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> DeptID { get; set; }
        public Nullable<int> No { get; set; }
        public string Name { get; set; }
        public string WorkLevel { get; set; }
        public string Workduty { get; set; }
        public string WorkUnit { get; set; }
        public string Gender { get; set; }
        public string DOB { get; set; }
        public Nullable<int> Age { get; set; }
        public string Phone { get; set; }
        public string IDCard { get; set; }
        public string Address { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public string Affix { get; set; }

        public string DeptName { get; set; }

    }
}
